#!/bin/sh /etc/rc.common

START=99

start()
{
    # set pin mux
    mt7688_pinmux set ephy gpio
    mt7688_pinmux set pwm0 gpio
    mt7688_pinmux set pwm1 gpio
    mt7688_pinmux set uart2 gpio

    # start mua service
    # main service MUST start first of all
    /usr/bin/mua_main_service &
    sleep 1
    # other service start after main service
    /usr/bin/mua_mqtt_service &
    /usr/bin/mua_miod_service &
    /usr/bin/mua_file_service &
    /usr/bin/mua_snd_service  &
    /usr/bin/mua_msg_service  &
    # test nfc, for demo only
    [ -x /usr/bin/nfcd ] && nfcd 2>&1 > /dev/null &
    sleep 5
    ubus call mua.main.service start {}
}
